
import com.sun.istack.NotNull;
import com.sun.istack.logging.Logger;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.awt.print.PrinterException;
import java.sql.Connection;
import java.util.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Erdal
 */
public class racun extends javax.swing.JFrame {

    /**
     * Creates new form racun
     */
    Connection conn = null;
    Statement stmt = null;
    ResultSet rs = null;
    PreparedStatement pst;
    
    public racun() {
        super("Racun");
        initComponents(); 
        conn = databaseConnection.connection();
        setvalues();
        setvalues2();
        CurrentDate();
        
        radnik.setBackground(new Color(255,255,255));
        model.setBackground(new Color(255,255,255));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        area = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        radnik = new javax.swing.JComboBox<>();
        model = new javax.swing.JComboBox<>();
        cena = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        prikaziracun = new javax.swing.JButton();
        print = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 192, 1));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 192, 1), new java.awt.Color(255, 192, 1), new java.awt.Color(255, 192, 1), new java.awt.Color(255, 192, 1)), "Racun", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        area.setColumns(20);
        area.setRows(5);
        jScrollPane1.setViewportView(area);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 500, 430));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Radnik:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 76, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Telefon:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 76, -1));

        radnik.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Item 2", "Item 3", "Item 4" }));
        radnik.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        radnik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radnikActionPerformed(evt);
            }
        });
        jPanel1.add(radnik, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 174, 39));

        model.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        model.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        model.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                modelItemStateChanged(evt);
            }
        });
        model.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                modelPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        model.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                modelKeyPressed(evt);
            }
        });
        jPanel1.add(model, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 174, 39));

        cena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cenaActionPerformed(evt);
            }
        });
        jPanel1.add(cena, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 174, 39));

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cena:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        prikaziracun.setText("Prikazi Racun");
        prikaziracun.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        prikaziracun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prikaziracunActionPerformed(evt);
            }
        });
        jPanel1.add(prikaziracun, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 475, 100, 35));

        print.setText("Print");
        print.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });
        jPanel1.add(print, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 475, 95, 35));

        jButton3.setText("Back");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 475, 95, 35));

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Vreme");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 286, 120, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 346, 120, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Datum");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("X");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 0, 50, 50));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Blockchain Technolog4.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 50, 50));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Blockchain Technology3.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 40, 50, 50));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Blockchain Technolog4.png"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 50, 50));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Blockchain Technology3.png"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 510, 50, 50));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Blockchain Technolog4.png"))); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 490, 50, 50));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Blockchain Technolog4.png"))); // NOI18N
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, 50, 50));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Blockchain Technology3.png"))); // NOI18N
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 50, 50));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Blockchain Technology3.png"))); // NOI18N
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 50, 50));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Blockchain Technolog4.png"))); // NOI18N
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, 50, 50));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Blockchain Technology3.png"))); // NOI18N
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 430, 50, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 530));

        jMenu1.setText("File");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem2.setText("Odjava");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(900, 554));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void setvalues()
{
   try
   {
      String qry="SELECT name FROM RADNIK";
      pst=conn.prepareStatement(qry);
      rs=pst.executeQuery();
      radnik.removeAllItems();
      while(rs.next())
      {
       radnik.addItem(rs.getString("name"));
      }
   }
   catch(SQLException e)
   {
	JOptionPane.showMessageDialog(null, e);
   }
}
       public void setvalues2()
{
   try
   {
      String qry="SELECT model FROM TELEFONI";
      pst=conn.prepareStatement(qry);
      rs=pst.executeQuery();
      model.removeAllItems();
      while(rs.next())
      {
       model.addItem(rs.getString("model"));
      }
   }
   catch(SQLException e)
   {
	JOptionPane.showMessageDialog(null, e);
   }
}
    
    
    
    
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        login object = new login();
        object.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        home object = new home();
        object.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void radnikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radnikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radnikActionPerformed

    private void modelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_modelKeyPressed
        // TODO add your handling code here:
     
            
    }//GEN-LAST:event_modelKeyPressed

    private void modelItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_modelItemStateChanged
      
    }//GEN-LAST:event_modelItemStateChanged

    private void modelPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_modelPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        String tmp = (String)model.getSelectedItem();
        String sql = "select * from TELEFONI where model=?";
        try{
            pst=conn.prepareStatement(sql);
            pst.setString(1, tmp);
            rs=pst.executeQuery();
            if(rs.next()){
                String add1 = rs.getString("Cena");
                cena.setText (add1);
            }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_modelPopupMenuWillBecomeInvisible

    private void prikaziracunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prikaziracunActionPerformed
        // TODO add your handling code here:
        area.setText("*********************************\n");
        area.setText(area.getText()+"*   Racun   *\n");
        area.setText(area.getText()+"*********************************\n");
        
        Date obj = new Date();
        
        String date = obj.toString();
        
        area.setText(area.getText()+"\n"+date+"\n\n");
        area.setText(area.getText()+"Cena: "+cena.getText()+"\n\n");
        area.setText(area.getText()+"Telefon prodao: "+radnik.getSelectedItem()+"\n\n");
        area.setText(area.getText()+"Model Telefona: "+model.getSelectedItem()+"\n\n");
       
    }//GEN-LAST:event_prikaziracunActionPerformed

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        // TODO add your handling code here:
        try{
            area.print();
        }
        catch(PrinterException e)
        {
            
        }
         try {
            stmt = conn.createStatement();
            String Radnik = radnik.getSelectedItem().toString();
            String Model = model.getSelectedItem().toString();
            String Cena = cena.getText(); 
            String sql = "INSERT INTO RACUN (radnik, model, cena)VALUES('"+Radnik+"', '"+Model+"', '"+Cena+"')";
            stmt.executeUpdate(sql); 
            clearAll();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_printActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void cenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cenaActionPerformed
public void clearAll(){
    radnik.setSelectedIndex(0);
    model.setSelectedIndex(0);
    cena.setText("");
      
}
    
    
    
    
    public void CurrentDate(){
        Thread clock;
        clock = new Thread(){
            public void run(){
                for(;;){
                   
                    Calendar cal=new GregorianCalendar();
                    int month=cal.get(Calendar.MONTH);
                    int year=cal.get(Calendar.YEAR);
                    int day=cal.get(Calendar.DAY_OF_MONTH);
                    jLabel6.setText(+day+"-"+(month+1)+"-"+year);
                   
                    int hour=cal.get(Calendar.HOUR);
                    int min=cal.get(Calendar.MINUTE);
                    int sec=cal.get(Calendar.SECOND);
                   
                    jLabel5.setText(+hour+":"+(min)+":"+sec);
         
                        try {
                            sleep(1000);
                        } catch (InterruptedException ex) {
                            java.util.logging.Logger.getLogger(racun.class.getName()).log(Level.SEVERE, null, ex);
                        
                    }
                   
                   
                }
            }
        };
        clock.start();
       
       
    }
  
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(racun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(racun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(racun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(racun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new racun().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea area;
    private javax.swing.JTextField cena;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> model;
    private javax.swing.JButton prikaziracun;
    private javax.swing.JButton print;
    private javax.swing.JComboBox<String> radnik;
    // End of variables declaration//GEN-END:variables
}
