
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.MessageFormat;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Erdal
 */
public final class telefoni extends javax.swing.JFrame {

    /**
     * Creates new form addTelefoni
     */
    Connection conn = null;
    Statement stmt = null;
    ResultSet rs = null;
    PreparedStatement pst;
    
    public telefoni() {
        super ("Dodaj Telefon");
        initComponents();
        
        conn = databaseConnection.connection();
        showRecord();
        
    }
public void showRecord(){
        
    
        try {
            stmt = conn.createStatement();
            String sql = "SELECT * FROM TELEFONI";
            ResultSet res = stmt.executeQuery(sql);
            jTable1.setModel(DbUtils.resultSetToTableModel(res));
            
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        print = new javax.swing.JButton();
        pretraga = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        Name3 = new javax.swing.JLabel();
        marka = new javax.swing.JTextField();
        Name1 = new javax.swing.JLabel();
        Email1 = new javax.swing.JLabel();
        model = new javax.swing.JTextField();
        Password1 = new javax.swing.JLabel();
        update = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        back = new javax.swing.JButton();
        add = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        cena = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 554));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 192, 1));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 192, 1), new java.awt.Color(255, 192, 1), new java.awt.Color(255, 192, 1), new java.awt.Color(255, 192, 1)), "Telefoni", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, 430, 420));

        print.setText("Print");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });
        jPanel1.add(print, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 460, 100, 35));

        pretraga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pretragaActionPerformed(evt);
            }
        });
        pretraga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pretragaKeyReleased(evt);
            }
        });
        jPanel1.add(pretraga, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 218, 29));

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Pretraga:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, 30));
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 218, 29));

        Name3.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        Name3.setForeground(new java.awt.Color(255, 255, 255));
        Name3.setText("Id:");
        jPanel1.add(Name3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 37, 30));
        jPanel1.add(marka, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 218, 29));

        Name1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        Name1.setForeground(new java.awt.Color(255, 255, 255));
        Name1.setText("Marka:");
        jPanel1.add(Name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 66, 30));

        Email1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        Email1.setForeground(new java.awt.Color(255, 255, 255));
        Email1.setText("Model:");
        jPanel1.add(Email1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 66, 30));
        jPanel1.add(model, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 218, 29));

        Password1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        Password1.setForeground(new java.awt.Color(255, 255, 255));
        Password1.setText("Cena:");
        jPanel1.add(Password1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 60, 30));

        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel1.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, 100, 35));

        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel1.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 390, 100, 35));

        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 100, 35));

        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel1.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 460, 100, 35));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("X");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 0, 50, 50));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Blockchain Technolog4.png"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 50, 50));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Blockchain Technology3.png"))); // NOI18N
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, -10, 50, 50));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Blockchain Technology3.png"))); // NOI18N
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 70, 50, 50));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Blockchain Technolog4.png"))); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, -10, 50, 50));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Blockchain Technology3.png"))); // NOI18N
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 500, 50, 50));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Blockchain Technolog4.png"))); // NOI18N
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 490, 50, 50));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Blockchain Technology3.png"))); // NOI18N
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, 50, 50));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Blockchain Technolog4.png"))); // NOI18N
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 50, 50));
        jPanel1.add(cena, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 218, 29));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 530));

        jMenu1.setText("File");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem2.setText("Odjava");
        jMenuItem2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(900, 554));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        login object = new login();
        object.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int row=jTable1.getSelectedRow();
        String Table_click=(jTable1.getModel().getValueAt(row, 0).toString());
        try{
            String sql="SELECT * FROM TELEFONI WHERE id='"+Table_click+"'";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();

            if(rs.next()){
                String add4=rs.getString("id");
                id.setText(add4);
                String add1=rs.getString("marka");
                marka.setText(add1);
                String add2=rs.getString("model");
                model.setText(add2);
                String add3=rs.getString("cena");
                cena.setText(add3);    
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        // TODO add your handling code here:
        MessageFormat header=new MessageFormat("Report Print");
        MessageFormat footer=new MessageFormat("Page(0,number,integer)");
        try{
            jTable1.print(JTable.PrintMode.NORMAL, header, footer);
        }catch(java.awt.print.PrinterException e){
            System.err.format("Cannot Print %s%n", e.getMessage());
        }

    }//GEN-LAST:event_printActionPerformed

    private void pretragaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pretragaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pretragaActionPerformed

    private void pretragaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pretragaKeyReleased
        // TODO add your handling code here:
        try{
            String sql="SELECT * FROM TELEFONI WHERE model=?";
            pst=conn.prepareStatement(sql);
            pst.setString(1, pretraga.getText());
            rs=pst.executeQuery();
            if(rs.next()){
                String add1=rs.getString("marka");
                marka.setText(add1);
                String add2=rs.getString("model");
                model.setText(add2);
                String add3=rs.getString("cena");
                cena.setText(add3);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_pretragaKeyReleased

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        try{
            stmt = conn.createStatement();
            int Id = Integer.parseInt(id.getText());
            String Marka = marka.getText();
            String Model = model.getText();
            String Cena = cena.getText();

            String sql = "UPDATE TELEFONI SET Marka = '"+Marka+"', Model = '"+Model+"',  Cena = '"+Cena+"' WHERE id = '"+Id+"'";

            stmt.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Uspesno ste izmenili podatke");

            showRecord();
            clearTextFieldsData();
        }catch(Exception e){JOptionPane.showMessageDialog(null, e);}
    }//GEN-LAST:event_updateActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        try{

            stmt = conn.createStatement();
            int Id = Integer.parseInt(id.getText());
            String sql = "DELETE FROM TELEFONI WHERE id = '"+Id+"'";
            stmt.executeUpdate(sql);

            JOptionPane.showMessageDialog(null, "Telefon je uspesno obrisan");

        }catch(Exception e){JOptionPane.showMessageDialog(null, e);}
        showRecord();
    }//GEN-LAST:event_deleteActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        home object = new home();
        object.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        try{
            stmt = conn.createStatement();
            String Marka = marka.getText();
            String Model = model.getText();
            String Cena = cena.getText();

            String sql = "INSERT INTO TELEFONI(marka, model, cena) values('"+Marka+"','"+Model+"','"+Cena+"')";
            stmt.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Uspesno ste ubacili telefon");
            showRecord();

        }catch(Exception e){JOptionPane.showMessageDialog(null, e);}
    }//GEN-LAST:event_addActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel6MouseClicked
 public void clearTextFieldsData(){
	id.setText("");
        marka.setText("");
	model.setText("");
	cena.setText("");
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telefoni.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telefoni.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telefoni.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telefoni.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telefoni().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Email1;
    private javax.swing.JLabel Name1;
    private javax.swing.JLabel Name3;
    private javax.swing.JLabel Password1;
    private javax.swing.JButton add;
    private javax.swing.JButton back;
    private javax.swing.JTextField cena;
    private javax.swing.JButton delete;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField marka;
    private javax.swing.JTextField model;
    private javax.swing.JTextField pretraga;
    private javax.swing.JButton print;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
